# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Update Racing Reference Data

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * 2-11 *" 
  # push:
  #  branches: [ main ]
  #pull_request:
  #  branches: [ main ]
jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.12"]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
        echo "deb http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee -a /etc/apt/sources.list.d/google-chrome.list
        sudo apt-get update -qqy
        sudo apt-get -qqy install google-chrome-stable
        CHROME_VERSION=$(google-chrome-stable --version)
        CHROME_FULL_VERSION=${CHROME_VERSION%%.*}
        CHROME_MAJOR_VERSION=${CHROME_FULL_VERSION//[!0-9]}
        sudo rm /etc/apt/sources.list.d/google-chrome.list
        export CHROMEDRIVER_VERSION=`curl -s https://chromedriver.storage.googleapis.com/LATEST_RELEASE_${CHROME_MAJOR_VERSION%%.*}`
        curl -L -O "https://chromedriver.storage.googleapis.com/${CHROMEDRIVER_VERSION}/chromedriver_linux64.zip"
        unzip chromedriver_linux64.zip && chmod +x chromedriver && sudo mv chromedriver /usr/local/bin
        export CHROMEDRIVER_VERSION=`curl -s https://chromedriver.storage.googleapis.com/LATEST_RELEASE_${CHROME_MAJOR_VERSION%%.*}`
        curl -L -O "https://chromedriver.storage.googleapis.com/${CHROMEDRIVER_VERSION}/chromedriver_linux64.zip"
        unzip chromedriver_linux64.zip && chmod +x chromedriver && sudo mv chromedriver /usr/local/bin
        chromedriver -version     
        python -m pip install --upgrade pip
        python -m pip install pandas
        python -m pip install requests
        python -m pip install beautifulsoup4
        python -m pip install lxml
        python -m pip install tqdm
        python -m pip install selenium
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: run Python Script
      run: |
        python parse_racing_reference.py
    - name: commit files
      run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git commit -m "Update Racing Reference data." -a
          
    - name: push changes
      uses: ad-m/github-push-action@v0.6.0
      with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
